import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowDown, ArrowRight, Atom, BookOpen, Check, ChevronDown, CircleHelp, Command, FlaskConical, Layers3, Play, RotateCcw, ShieldCheck, Shuffle, Sparkles, Terminal, X } from 'lucide-react';
import './style.css';

const mod=(n,m)=>((n%m)+m)%m;
function gcd(a,b){while(b)[a,b]=[b,a%b];return a}
function pow(a,n,m){let r=1;while(n){if(n&1)r=mod(r*a,m);a=mod(a*a,m);n>>=1}return r}
function App(){
 const [modulus,setModulus]=useState(7); const [left,setLeft]=useState(3); const [right,setRight]=useState(5); const [operation,setOperation]=useState('+'); const [running,setRunning]=useState(false); const [seed,setSeed]=useState(0); const [testPassed,setTestPassed]=useState(null);
 const prime=useMemo(()=>{for(let i=2;i*i<=modulus;i++)if(modulus%i===0)return false;return modulus>1},[modulus]);
 const result=operation==='+'?mod(left+right,modulus):operation==='×'?mod(left*right,modulus):mod(left-right,modulus);
 const data=useMemo(()=>{const n=modulus, values=Array.from({length:n},(_,i)=>i); return {values,table:values.map(a=>values.map(b=>operation==='+'?mod(a+b,n):operation==='×'?mod(a*b,n):mod(a-b,n))) }},[modulus,operation]);
 function runTests(){setRunning(true);window.setTimeout(()=>{let passed=true;for(let i=0;i<1000;i++){const a=Math.floor(Math.random()*modulus),b=Math.floor(Math.random()*modulus),c=Math.floor(Math.random()*modulus);const op=(x,y)=>operation==='+'?mod(x+y,modulus):operation==='×'?mod(x*y,modulus):mod(x-y,modulus);if(op(op(a,b),c)!==op(a,op(b,c))){passed=false;break}}setTestPassed(passed);setSeed(v=>v+1);setRunning(false)},30)}
 const checks=[['Domkniętość','wynik zawsze należy do zbioru'],['Łączność','(a ⊙ b) ⊙ c = a ⊙ (b ⊙ c)'],['Element neutralny',operation==='+'?'0 ⊙ a = a':'1 ⊙ a = a'],['Element odwrotny',operation==='+'?'a + (−a) = 0':'a · a⁻¹ = 1 (dla a ≠ 0)']];
 return <><header className="top"><a className="brand" href="#"><span className="brand-icon"><Atom size={19}/></span> algebra<span className="brand-light">lab</span><span className="version">EDYCJA 01</span></a><nav><a href="#odkrywaj">Odkrywaj</a><a href="#laboratorium">Laboratorium</a><a href="#projekt">Projekt</a></nav><a className="top-cta" href="#laboratorium">Zacznij eksperyment <ArrowRight size={15}/></a></header>
 <main><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="pulse"/> INTERAKTYWNY PRZEWODNIK PO ALGEBRZE</div><h1>Matematyka ma<br/>swoje <span>reguły gry.</span></h1><p className="lead">Odkryj struktury, które porządkują liczby, symetrie i operacje. Zamiast uczyć się definicji na pamięć — zobacz je w działaniu.</p><div className="hero-actions"><a className="button primary" href="#odkrywaj"><Sparkles size={16}/> Odkryj struktury <ArrowDown size={15}/></a><a className="text-link" href="#laboratorium"><Play size={15}/> Przejdź do laboratorium</a></div><div className="hero-proof"><span className="avatars"><i>∑</i><i>π</i><i>∞</i></span><span>Matematyka spotyka się z kodem</span><span className="proof-sep">·</span><span>bez instalacji</span></div></div>
 <div className="hero-art"><div className="art-grid"/><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit orbit-three"/><div className="art-core"><span>G</span><small>STRUKTURA</small></div><div className="float-chip chip-a"><span className="chip-dot purple"/> a ⊙ e = a</div><div className="float-chip chip-b"><span className="chip-dot green"/> łączność ✓</div><div className="float-chip chip-c">ℤ / 7ℤ</div><div className="art-caption"><span className="caption-line"/> JEDNO PRAWO. NIESKOŃCZENIE ZASTOSOWAŃ.</div></div></section>
 <section className="metrics"><div><strong>01</strong><span>zestaw pojęć</span></div><div><strong>04</strong><span>struktury algebraiczne</span></div><div><strong>∞</strong><span>możliwych eksperymentów</span></div><div className="metrics-note"><span className="mini-spark">✳</span> Poznawaj przez eksperymentowanie</div></section>
 <section className="section discover" id="odkrywaj"><div className="section-head"><div><div className="eyebrow">MAPA POJĘĆ <span className="short-rule"/></div><h2>Od prostych reguł<br/>do wielkich struktur.</h2></div><p>Każda struktura dodaje nowe zasady. Poznaj je po kolei i zobacz, jak z kilku prostych aksjomatów powstaje cały matematyczny świat.</p></div><div className="concepts">
 <article className="concept"><div className="concept-top"><span className="concept-icon lavender"><Layers3 size={19}/></span><span className="concept-index">01 / FUNDAMENT</span></div><h3>Półgrupa</h3><p>Zbiór i działanie, które jest łączne. To minimalny porządek, od którego zaczyna się algebra.</p><div className="formula">(a ⊙ b) ⊙ c = a ⊙ (b ⊙ c)</div><div className="concept-foot"><span className="dot lavender-dot"/> 1 aksjomat <span className="line-fill"/> <a href="#laboratorium">poznaj <ArrowRight size={13}/></a></div></article>
 <article className="concept"><div className="concept-top"><span className="concept-icon mint"><Shuffle size={19}/></span><span className="concept-index">02 / SYMETRIA</span></div><h3>Grupa</h3><p>Każda operacja ma swoje cofnięcie. Grupy opisują symetrie i ruchy, które można odwrócić.</p><div className="formula">a ⊙ a⁻¹ = e</div><div className="concept-foot"><span className="dot mint-dot"/> 4 aksjomaty <span className="line-fill"/> <a href="#laboratorium">poznaj <ArrowRight size={13}/></a></div></article>
 <article className="concept"><div className="concept-top"><span className="concept-icon peach"><Command size={19}/></span><span className="concept-index">03 / DWIE OPERACJE</span></div><h3>Pierścień</h3><p>Dodawanie i mnożenie współpracują dzięki prawu rozdzielności. Dom na liczby całkowite.</p><div className="formula">a · (b + c) = a · b + a · c</div><div className="concept-foot"><span className="dot peach-dot"/> 2 działania <span className="line-fill"/> <a href="#laboratorium">poznaj <ArrowRight size={13}/></a></div></article>
 <article className="concept"><div className="concept-top"><span className="concept-icon blue"><Sparkles size={19}/></span><span className="concept-index">04 / DZIELENIE</span></div><h3>Ciało</h3><p>W pierścieniu, w którym można dzielić przez każdy niezerowy element. Tu dzieje się kryptografia.</p><div className="formula">a ≠ 0 ⇒ ∃ a⁻¹ : a · a⁻¹ = 1</div><div className="concept-foot"><span className="dot blue-dot"/> 2 działania <span className="line-fill"/> <a href="#laboratorium">poznaj <ArrowRight size={13}/></a></div></article>
 </div><div className="progression"><span>PÓŁGRUPA</span><ArrowRight/><span>MONOID</span><ArrowRight/><span>GRUPA</span><ArrowRight/><span>PIERŚCIEŃ</span><ArrowRight/><span>CIAŁO</span><span className="progression-note">każdy krok dodaje nowe własności →</span></div></section>
 <section className="lab-section" id="laboratorium"><div className="lab-header"><div><div className="eyebrow light-eyebrow"><span className="pulse"/> LABORATORIUM ALGEBRAICZNE</div><h2>Nie wierz na słowo.<br/><span>Sprawdź samodzielnie.</span></h2></div><p>Zmień parametry, wykonaj działanie i zobacz, jak aksjomaty ujawniają się w praktyce.</p></div><div className="lab"><div className="lab-controls"><div className="panel-title"><span className="panel-icon"><FlaskConical size={16}/></span><div><b>Eksperyment 01</b><small>ARYTMETYKA MODULARNA</small></div><button className="icon-button" onClick={()=>{setLeft(3);setRight(5);setModulus(7);setOperation('+')}} title="Resetuj"><RotateCcw size={15}/></button></div><div className="field-label">WYBIERZ DZIAŁANIE</div><div className="op-select">{['+','×','−'].map(op=><button key={op} className={operation===op?'selected':''} onClick={()=>setOperation(op)}>{op}</button>)}</div><div className="field-label">LICZBY MODULO <span className="select-wrap"><select value={modulus} onChange={e=>setModulus(+e.target.value)}>{[5,7,8,11,13].map(n=><option key={n} value={n}>{n}</option>)}</select><ChevronDown size={13}/></span></div><div className="number-inputs"><label><span>a</span><input type="number" min="0" max={modulus-1} value={left} onChange={e=>setLeft(mod(+e.target.value,modulus))}/></label><span className="input-operation">{operation}</span><label><span>b</span><input type="number" min="0" max={modulus-1} value={right} onChange={e=>setRight(mod(+e.target.value,modulus))}/></label></div><div className="result-box"><span>WYNIK W ℤ/{modulus}ℤ</span><strong>{result}</strong><small>{left} {operation} {right} ≡ {result} (mod {modulus})</small></div><button className="button run-button" onClick={runTests}><Play size={15} fill="currentColor"/> Wykonaj działanie <ArrowRight size={15}/></button></div>
 <div className="lab-right"><div className="table-panel"><div className="table-head"><div><span className="tiny-label">TABELA DZIAŁANIA</span><h3>{operation==='+'?'Dodawanie':operation==='×'?'Mnożenie':'Odejmowanie'} modulo {modulus}</h3></div><span className="field-badge">{prime?'CIAŁO':'PIERŚCIEŃ'}</span></div><div className="table-scroll"><table><thead><tr><th>{operation}</th>{data.values.map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{data.values.map((a,i)=><tr key={a}><th>{a}</th>{data.table[i].map((v,j)=><td key={j} className={a===left&&data.values[j]===right?'cell-active':''}>{v}</td>)}</tr>)}</tbody></table></div><div className="table-note"><CircleHelp size={14}/> Każda komórka to wynik działania dla liczby z wiersza i kolumny.</div></div>
 <div className="axiom-panel"><div className="axiom-title"><div><ShieldCheck size={16}/><b>Własności do sprawdzenia</b></div><span className="test-count">{seed?`OSTATNIO: 1 000 PRÓB`:'TRYB EDUKACYJNY'}</span></div><div className="checks">{checks.map(([name,formula],i)=><div className="check-row" key={name}><span className={`check-state ${i===3&&operation==='×'&&!prime?'warning':''}`}>{i===3&&operation==='×'&&!prime?<CircleHelp size={13}/>:testPassed===false&&i===1?<X size={13}/>:<Check size={13}/>}</span><span className="check-name">{name}</span><code>{formula}</code></div>)}</div><button className="test-button" onClick={runTests} disabled={running}>{running?<><span className="spinner"/> Sprawdzam losowe przykłady…</>:<> <Play size={13}/> Uruchom 1 000 prób <span>→</span></>}</button></div></div></div><div className="lab-footnote"><span>ⓘ</span> {seed?`Łączność dla działania ${operation} modulo ${modulus}: ${testPassed?'nie znaleziono kontrprzykładu w 1 000 próbach.':'znaleziono kontrprzykład.'} To test losowy, nie dowód.`:'Testy losowe pomagają znaleźć błędy, ale nie zastępują dowodu matematycznego.'}</div></section>
 <section className="proof-section" id="projekt"><div className="proof-copy"><div className="eyebrow">MATEMATYKA W KODZIE <span className="short-rule"/></div><h2>Aksjomaty to<br/>najlepsze testy.</h2><p>W programowaniu możesz opisać prawa matematyczne jako własności, które powinny zachodzić dla każdej próbki danych. To świetny sposób na sprawdzanie implementacji — i rozumienie, co naprawdę mówi definicja.</p><a className="button dark-button" href="#laboratorium"><BookOpen size={15}/> Zobacz to w praktyce <ArrowRight size={15}/></a></div><div className="code-card"><div className="code-top"><div className="window-dots"><i/><i/><i/></div><span>group_properties.rs</span><span className="rust-tag">RUST</span></div><pre><code><span className="code-purple">proptest!</span> {'{'}<br/>  <span className="code-green">#[test]</span><br/>  <span className="code-blue">fn</span> <span className="code-yellow">addition_is_associative</span>(<br/>    a <span className="code-blue">in</span> <span className="code-purple">any</span>&lt;<span className="code-teal">ModInt</span>&gt;(),<br/>    b <span className="code-blue">in</span> <span className="code-purple">any</span>&lt;<span className="code-teal">ModInt</span>&gt;(),<br/>    c <span className="code-blue">in</span> <span className="code-purple">any</span>&lt;<span className="code-teal">ModInt</span>&gt;(),<br/>  ) {'{'}<br/>    <span className="code-blue">assert_eq!</span>(<br/>      (a + b) + c,<br/>      a + (b + c), <span className="code-comment">// prawo łączności</span><br/>    );<br/>  {'}'}<br/>{'}'}</code></pre><div className="code-foot"><span><span className="green-dot"/> 1 000 przypadków testowych</span><span>QuickCheck · proptest · Hypothesis</span></div></div></section>
 <section className="closing"><div className="closing-symbol">∑</div><div><div className="eyebrow">TWÓJ NASTĘPNY KROK</div><h2>Abstrakcja zaczyna się<br/>od <span>jednego pytania.</span></h2><p>Co się stanie, jeśli zmienisz reguły?</p></div><a className="button primary" href="#laboratorium">Wróć do laboratorium <ArrowRight size={15}/></a></section>
 <footer><a className="brand footer-brand" href="#"><span className="brand-icon"><Atom size={17}/></span> algebra<span className="brand-light">lab</span></a><span>Interaktywny wstęp do struktur algebraicznych</span><span>Stworzone do odkrywania. Bez bazy danych.</span></footer></main></>;
}

createRoot(document.getElementById('root')).render(<App/>);
